/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import modelo.Estudiante;
import modelo.InscripcionMateria;
import modelo.Materia;
import javax.swing.JOptionPane;
import javax.swing.JButton;

/**
 *
 * @author Martina Diesenberg
 */
public class MateriaView extends javax.swing.JFrame {
    
    private Estudiante estudiante;
    private DefaultTableModel modeloTabla;
    private DefaultListModel<String> modeloLista;
    private Controlador.EstudianteControlador controlador;
    private java.awt.CardLayout cardLayout;
    private javax.swing.JPanel panelCard;
    private javax.swing.JPanel panelPerfil;
    

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MateriaView.class.getName());

    /**
     * Creates new form MateriaView
     */
    public MateriaView(Estudiante estudiante) {
        initComponents();
        this.controlador = new Controlador.EstudianteControlador(estudiante);
        this.estudiante = estudiante;
        lblUsuarioYLegajo.setText("Alumno: " + estudiante.getNombre() + " | Legajo: " + estudiante.getLegajo());

        modeloTabla = new DefaultTableModel(new String[]{"Materia", "Condicion", "Asistencia %", "Promedio"}, 0) {
        public boolean isCellEditable(int row, int column) {
        return false;
    
        }
    };
        jTable1.setModel(modeloTabla);

        modeloLista = new DefaultListModel<>();

        actualizarVistas();
        jTable1.getSelectionModel().addListSelectionListener(e -> {
        int fila = jTable1.getSelectedRow();
        if (fila >= 0) {
            txtNombre.setText((String) jTable1.getValueAt(fila, 0));
            InscripcionMateria im = buscarPorNombre((String) jTable1.getValueAt(fila, 0));
            if (im != null) txtCodigo.setText(im.getMateria().getCodigo());
        }
    });
        
        panelPerfil = new javax.swing.JPanel();
        panelPerfil.setLayout(new java.awt.GridLayout(6, 1, 5, 10));
        panelPerfil.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 40, 20, 40));

        panelPerfil.add(new JLabel("Perfil del Estudiante", JLabel.CENTER));
        panelPerfil.add(new JLabel("Nombre: " + estudiante.getNombre(), JLabel.CENTER));
        panelPerfil.add(new JLabel("Legajo: " + estudiante.getLegajo(), JLabel.CENTER));
        panelPerfil.add(new JLabel("Carrera: " + estudiante.getCarrera(), JLabel.CENTER));
        panelPerfil.add(new JLabel("Año de ingreso: " + estudiante.getAnioIngreso(), JLabel.CENTER));

        JButton btnVolver = new JButton("← Volver");
        btnVolver.addActionListener(e -> cardLayout.show(panelCard, "main"));
        panelPerfil.add(btnVolver);

        // CardLayout
        cardLayout = new java.awt.CardLayout();
        panelCard = new javax.swing.JPanel(cardLayout);
        panelCard.add(jTabbedPane1, "main");
        panelCard.add(panelPerfil, "perfil");

        getContentPane().removeAll();
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(lblUsuarioYLegajo, java.awt.BorderLayout.NORTH);
        getContentPane().add(panelCard, java.awt.BorderLayout.CENTER);

        cardLayout.show(panelCard, "main");
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblPromedio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        btnInscribir = new javax.swing.JButton();
        btnRegistrarAsistencia = new javax.swing.JButton();
        btnRegistrarNota = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblNombreM = new javax.swing.JLabel();
        lblCodigoM = new javax.swing.JLabel();
        lblAdv = new javax.swing.JLabel();
        lblUsuarioYLegajo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItemEstadisticas = new javax.swing.JCheckBoxMenuItem();
        jMenuItemRiesgo = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setName("Reportes"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null},
                {"", null, null, null},
                {"", null, null, null},
                {"", null, null, null}
            },
            new String [] {
                "Materia", "Condición", "Asistencia %", "Promedio"
            }
        ));
        jTable1.setShowHorizontalLines(true);
        jTable1.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTable1);

        lblPromedio.setText("Promedio General: ");

        jLabel3.setText("Buscar Materia:");

        txtMateria.setText("Matematica I");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lblPromedio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );

        jTabbedPane1.addTab("Materias", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(597, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Asistencia", jPanel5);

        btnInscribir.setText("Inscribir Materia");
        btnInscribir.addActionListener(this::btnInscribirActionPerformed);

        btnRegistrarAsistencia.setText("Registrar Asistencia");
        btnRegistrarAsistencia.addActionListener(this::btnRegistrarAsistenciaActionPerformed);

        btnRegistrarNota.setText("Registrar Nota");
        btnRegistrarNota.addActionListener(this::btnRegistrarNotaActionPerformed);

        btnBaja.setText("Dar de Baja");
        btnBaja.addActionListener(this::btnBajaActionPerformed);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Materia"));

        txtCodigo.setEditable(false);

        btnGuardar.setText("Guardar cambios");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        lblNombreM.setText("Nombre de la materia:");

        lblCodigoM.setText("Código de la materia:");

        lblAdv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAdv.setText("Primero, seleccione la materia que desee editar en la tabla");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblCodigoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNombreM, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(202, 202, 202))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblAdv)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoM)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegistrarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarNota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBaja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnRegistrarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jTabbedPane1.addTab("Registrar", jPanel6);

        lblUsuarioYLegajo.setText("Usuario y Legajo");

        jMenu1.setText("Archivo");

        jMenuItem4.setText("Cerrar");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("REPORTES");

        jMenuItem1.setText("Situación General");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Materias en Riesgo");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Aprobadas");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu2.add(jMenuItem3);

        jMenuItemEstadisticas.setSelected(true);
        jMenuItemEstadisticas.setText("Estadísticas de Aprobadas");
        jMenuItemEstadisticas.addActionListener(this::jMenuItemEstadisticasActionPerformed);
        jMenu2.add(jMenuItemEstadisticas);

        jMenuItemRiesgo.setText("Materias en Riesgo Ordenadas");
        jMenuItemRiesgo.addActionListener(this::jMenuItemRiesgoActionPerformed);
        jMenu2.add(jMenuItemRiesgo);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioYLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblUsuarioYLegajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private InscripcionMateria buscarPorNombre(String nombre) {
        for (InscripcionMateria im : estudiante.getMaterias()) {
        if (im.getMateria().getNombre().equals(nombre)) {
            return im;
        }
    }
    return null;
    }
    
    private void btnRegistrarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAsistenciaActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una materia en la tabla primero.");
            return;
        }
        String nombre = (String) jTable1.getValueAt(fila, 0);
        InscripcionMateria im = buscarPorNombre(nombre);
        if (im == null) return;
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Estuvo presente en " + nombre + "?", "Asistencia", JOptionPane.YES_NO_OPTION);
        im.registrarAsistencia(respuesta == JOptionPane.YES_OPTION);
        if (im.getPorcentajeAsistencia() < 75) {
            JOptionPane.showMessageDialog(this, 
                "Si la asistencia baja del 75% se pierde la regularidad. Asistencia actual: " + 
                String.format("%.0f", im.getPorcentajeAsistencia()) + "%", 
                "Alerta", JOptionPane.WARNING_MESSAGE);
        } else if (im.getPorcentajeAsistencia() <= 85) {
            JOptionPane.showMessageDialog(this, 
                "Asistencia en zona de riesgo: " + String.format("%.0f", im.getPorcentajeAsistencia()) + 
                "%. Si baja del 75% se pierde la regularidad.", 
                "Alerta", JOptionPane.WARNING_MESSAGE);
        }
        new dao.EstudianteDAO().guardar(estudiante);
        actualizarVistas();
    }//GEN-LAST:event_btnRegistrarAsistenciaActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog("Nombre de la materia:");
        if (nombre == null || nombre.trim().isEmpty()) return;
        String codigo = JOptionPane.showInputDialog("Codigo de la materia:");
        if (codigo == null || codigo.trim().isEmpty()) return;
        String clasesStr = JOptionPane.showInputDialog("Total de clases:");
        if (clasesStr == null) return;
        Materia m = new Materia();
        m.setNombre(nombre);
        m.setCodigo(codigo);
        estudiante.inscribirse(m, Integer.parseInt(clasesStr));
        new dao.EstudianteDAO().guardar(estudiante);
        actualizarVistas();

    }//GEN-LAST:event_btnInscribirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelCard, "perfil");

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnRegistrarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNotaActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una materia en la tabla primero.");
            return;
        }
        String nombre = (String) jTable1.getValueAt(fila, 0);
        InscripcionMateria im = buscarPorNombre(nombre);
        if (im == null) return;
        String notaStr = JOptionPane.showInputDialog("Ingrese la nota (0-10):");
        if (notaStr == null) return;
        im.agregarNota(Double.parseDouble(notaStr));
        new dao.EstudianteDAO().guardar(estudiante);
        actualizarVistas();
    }//GEN-LAST:event_btnRegistrarNotaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una materia en la tabla primero.");
            return;
        }
        String nombre = (String) jTable1.getValueAt(fila, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que querés dar de baja " + nombre + "?", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            estudiante.darDeBaja(nombre);
            new dao.EstudianteDAO().guardar(estudiante);
            actualizarVistas();
        }
       
    }//GEN-LAST:event_btnBajaActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.out.println("Materias del estudiante: " + estudiante.getMaterias().size());
        for (InscripcionMateria im : estudiante.getMaterias()) {
            System.out.println(im.getMateria().getNombre() + " - " + im.getPorcentajeAsistencia() + "% - aprobada: " + im.estaAprobada());
        }

        StringBuilder sb = new StringBuilder("Materias en riesgo:\n");
        boolean hay = false;
        for (InscripcionMateria im : estudiante.getMaterias()) {
            double asistencia = im.getPorcentajeAsistencia();
            if (asistencia >= 75 && asistencia <= 85) {
                sb.append("- ").append(im.getMateria().getNombre())
                  .append(" (").append(String.format("%.0f", asistencia)).append("%)\n");
                hay = true;
            }
        }
        if (!hay) sb.append("No hay materias en riesgo.");
        JOptionPane.showMessageDialog(this, sb.toString(), "Materias en riesgo", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder("Materias aprobadas:\n");
        boolean hayAprobadas = false;
        for (InscripcionMateria im : estudiante.getMaterias()) {
            if (im.estaAprobada()) {
                sb.append("- ").append(im.getMateria().getNombre())
                  .append(" (promedio: ").append(String.format("%.2f", im.getPromedio())).append(")\n");
                hayAprobadas = true;
            }
        }
        if (!hayAprobadas) sb.append("No hay materias aprobadas.");
        JOptionPane.showMessageDialog(this, sb.toString(), "Aprobadas", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una materia primero.");
            return;
        }
        String nombreViejo = (String) jTable1.getValueAt(fila, 0);
        String nombreNuevo = txtNombre.getText().trim();
        if (nombreNuevo.isEmpty()) return;

        InscripcionMateria im = buscarPorNombre(nombreViejo);
        if (im != null) {
            im.getMateria().setNombre(nombreNuevo);
            jTable1.setValueAt(nombreNuevo, fila, 0);
            new dao.EstudianteDAO().guardar(estudiante);
            JOptionPane.showMessageDialog(this, "Cambios guardados.");
            actualizarVistas();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jMenuItemEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEstadisticasActionPerformed
    
    double max = Double.MIN_VALUE;
    double min = Double.MAX_VALUE;
    double suma = 0;
    int cantidad = 0;

    for (InscripcionMateria im : estudiante.getMaterias()) {

    if (im.estaAprobada()) {

        double nota = im.getPromedio();

        if (nota > max) max = nota;
        if (nota < min) min = nota;

        suma += nota;
        cantidad++;
    }
    }

    if (cantidad == 0) {
        JOptionPane.showMessageDialog(
                this,
                "No hay materias aprobadas."
        );
        return;
    }

    double promedio = suma / cantidad;

    String mensaje =
        "Nota máxima: " + String.format("%.2f", max)
        + "\nNota mínima: " + String.format("%.2f", min)
        + "\nPromedio: " + String.format("%.2f", promedio);

    JOptionPane.showMessageDialog(
        this,
        mensaje,
        "Estadísticas",
        JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_jMenuItemEstadisticasActionPerformed

    private void jMenuItemRiesgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRiesgoActionPerformed
    java.util.ArrayList<InscripcionMateria> riesgo = new java.util.ArrayList<>();

    for (InscripcionMateria im : estudiante.getMaterias()) {

    double asistencia = im.getPorcentajeAsistencia();

    if (asistencia >= 75 && asistencia <= 85) {
        riesgo.add(im);
        }
    }

    riesgo.sort((a, b) ->
        Double.compare(
                a.getPorcentajeAsistencia(),
                b.getPorcentajeAsistencia()
        )
    );

    StringBuilder sb = new StringBuilder();

    for (InscripcionMateria im : riesgo) {

    sb.append(im.getMateria().getNombre())
      .append(" - ")
      .append(String.format("%.0f%%",
              im.getPorcentajeAsistencia()))
      .append("\n");
    }

    if (riesgo.isEmpty()) {
    sb.append("No hay materias en riesgo.");
    }

    JOptionPane.showMessageDialog(
        this,
        sb.toString(),
        "Materias en Riesgo",
        JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_jMenuItemRiesgoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

    String buscar = txtMateria.getText().trim();

    if (buscar.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "Ingrese un nombre o código.");
        return;
    }

    for (int i = 0; i < jTable1.getRowCount(); i++) {

        String nombre = jTable1.getValueAt(i, 0).toString();

        if (nombre.equalsIgnoreCase(buscar)) {

            jTable1.setRowSelectionInterval(i, i);

            jTable1.scrollRectToVisible(
                    jTable1.getCellRect(i, 0, true)
            );

            return;
        }
    }

    for (int i = 0; i < estudiante.getMaterias().size(); i++) {

        InscripcionMateria im = estudiante.getMaterias().get(i);

        if (im.getMateria().getCodigo() != null
                && im.getMateria().getCodigo().equalsIgnoreCase(buscar)) {

            jTable1.setRowSelectionInterval(i, i);

            jTable1.scrollRectToVisible(
                    jTable1.getCellRect(i, 0, true)
            );

            return;
        }
    }

    JOptionPane.showMessageDialog(
            this,
            "Materia no encontrada."
    );       
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        dao.EstudianteDAO daoE = new dao.EstudianteDAO();
        Estudiante e = daoE.leer();
        if (e == null) {
            e = new Estudiante("Martina", "12345", "Informatica", 2022);
            Materia m1 = new Materia();
            m1.setNombre("Matematica I");
            m1.setCodigo("MAT");
            e.inscribirse(m1, 10);
            for (int i = 0; i < 8; i++) e.getInscripcion("MAT").registrarAsistencia(true);
            e.getInscripcion("MAT").agregarNota(8.0);
            Materia m2 = new Materia();
            m2.setNombre("Programacion II");
            m2.setCodigo("PRO");
            e.inscribirse(m2, 10);
            for (int i = 0; i < 8; i++) e.getInscripcion("PRO").registrarAsistencia(true);
            e.getInscripcion("PRO").agregarNota(6.5);
            daoE.guardar(e);
        }
        // sincronizar inscripciones con el archivo
        dao.InscripcionDAO inscDao = new dao.InscripcionDAO();
        inscDao.guardarTodas(e.getMaterias());
        new MateriaView(e).setVisible(true);
    });
    
        
    
    }
    
    public Controlador.EstudianteControlador getControlador() {
        return controlador;
    }
    public void actualizarVistas() {
        actualizarTabla();
        actualizarAsistencia();
        actualizarLista();
        actualizarReportes();
    }
    
    private void actualizarTabla() {
        modeloTabla.setRowCount(0);
        for (InscripcionMateria im : estudiante.getMaterias()) {
            modeloTabla.addRow(new Object[]{
                im.getMateria().getNombre(),
                im.getCondicion(),
                String.format("%.0f%%", im.getPorcentajeAsistencia()),
                String.format("%.2f", im.getPromedio())
            });
        }
        lblPromedio.setText("Promedio General: " + String.format("%.2f", estudiante.getPromedioGeneral()));
    }

    private void actualizarAsistencia() {
        jPanel5.removeAll();
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));
        for (InscripcionMateria im : estudiante.getMaterias()) {
            JLabel lbl = new JLabel(im.getMateria().getNombre());
            lbl.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            JProgressBar bar = new JProgressBar(0, 100);
            bar.setValue((int) im.getPorcentajeAsistencia());
            bar.setStringPainted(true);
            bar.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 20));
            bar.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            jPanel5.add(lbl);
            jPanel5.add(bar);
            jPanel5.add(javax.swing.Box.createVerticalStrut(8));
        }
        jPanel5.revalidate();
        jPanel5.repaint();
    }

    private void actualizarLista() {
        modeloLista.clear();
        for (InscripcionMateria im : estudiante.getMaterias()) {
            double asistencia = im.getPorcentajeAsistencia();
            if (asistencia >= 75 && asistencia <= 85) {
                modeloLista.addElement(im.getMateria().getNombre() + " — " +
                    String.format("%.0f", asistencia) + "%");
            }
        }
    }


    private void actualizarReportes() {
    DefaultTableModel modeloRiesgo = new DefaultTableModel(
        new String[]{"Materia", "Asistencia %"}, 0) {
        public boolean isCellEditable(int r, int c) { return false; }
    };

    java.util.ArrayList<InscripcionMateria> riesgo = new java.util.ArrayList<>();
    for (InscripcionMateria im : controlador.getInscripciones()) {
        double asistencia = im.getPorcentajeAsistencia();
        if (asistencia >= 75 && asistencia <= 85) {
            riesgo.add(im);
        }
    }
    riesgo.sort((a, b) -> Double.compare(a.getPorcentajeAsistencia(), b.getPorcentajeAsistencia()));

    for (InscripcionMateria im : riesgo) {
        modeloRiesgo.addRow(new Object[]{
            im.getMateria().getNombre(),
            String.format("%.0f%%", im.getPorcentajeAsistencia())
        });
    }
   

    java.util.ArrayList<Double> promedios = new java.util.ArrayList<>();
    for (InscripcionMateria im : estudiante.getMaterias()) {
        if (im.estaAprobada()) {
            promedios.add(im.getPromedio());
        }
    }
   
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnRegistrarAsistencia;
    private javax.swing.JButton btnRegistrarNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JCheckBoxMenuItem jMenuItemEstadisticas;
    private javax.swing.JMenuItem jMenuItemRiesgo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAdv;
    private javax.swing.JLabel lblCodigoM;
    private javax.swing.JLabel lblNombreM;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JLabel lblUsuarioYLegajo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
